"""Calendar colum fix: topic -> topics

Revision ID: 5341675c43b6
Revises: 5661c2d80291
Create Date: 2026-03-30 22:31:01.586808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5341675c43b6'
down_revision: Union[str, Sequence[str], None] = '5661c2d80291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendars', sa.Column('topics', sa.JSON(), nullable=False, comment='게스트와 나눌 주제들'))
    op.drop_column('calendars', 'topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendars', sa.Column('topic', mysql.JSON(), nullable=False, comment='게스트와 나눌 주제들'))
    op.drop_column('calendars', 'topics')
    # ### end Alembic commands ###
