"""User model fix

Revision ID: 5661c2d80291
Revises: 4e7a150813a3
Create Date: 2026-03-14 21:07:19.056398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5661c2d80291'
down_revision: Union[str, Sequence[str], None] = '4e7a150813a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='사용자 비밀번호'))
    op.drop_index(op.f('username'), table_name='users')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=255), nullable=False, comment='사용자 비밀번호'))
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
